#+--------------------------------------------------------------------+
#| products/model.coffee
#+--------------------------------------------------------------------+
#| Copyright fivetwofivetwo, LLC (c) 2014
#+--------------------------------------------------------------------+
#|
#| This file is a part of iwishua
#|
#| This file is subject to the terms and conditions defined in
#| file 'license.md', which is part of this source code package.
#|
#+--------------------------------------------------------------------+
#
# Sets up the model with client-side metadata 
# and any other model extensions we need (none so far)
#
angular.module('iwishua')
.factory 'model', 
  ($log, $q, breeze, logger) ->

    new class ProductsModel

      constructor: ->
        logger.log "ProductsModel initialized"


      setModel: (manager) ->

        # Associate the metadata with the manager's data service
        store = manager.metadataStore
        store.addDataService(manager.dataService)

        helper = new breeze.config.MetadataHelper('Model', breeze.AutoGeneratedKeyType.Identity)
        helper.addTypeToStore store,
          name: "iwishuaproducts",
          defaultResourceName: "iwishuaproducts",
          dataProperties:
            id:                   type: breeze.DataType.Guid
            productId:            type: breeze.DataType.Guid
            productTitle:         maxLength: 4000
            productDescription:   maxLength: 4000
            productImageUrl:      maxLength: 4000
            productBuyUrl:        maxLength: 4000
            productKeywords:      maxLength: 4000
            impressionUrl:        maxLength: 4000
            isPublished:          type: breeze.DataType.Boolean

        $q.when(manager)

