// Generated by CoffeeScript 1.7.1
(function() {
  define('./services', function(require, exports, module) {
    var facebook_app_id;
    facebook_app_id = '1495109164043412';
    require('./controllers');
    require('./directives');
    require('./filters');
    require('./services');
    return angular.module('iwishua', ['ngTouch', 'ngRoute', 'ngFacebook', 'breeze.angular', 'iwishua.services', 'iwishua.filters', 'iwishua.directives', 'iwishua.controllers']).config(function($routeProvider, $facebookProvider) {
      $facebookProvider.setAppId("" + facebook_app_id);
      $facebookProvider.setPermissions("publish_stream");
      $facebookProvider.setCustomInit({
        xfbml: true,
        version: 'v2.0'
      });
      return $routeProvider.when('/', {
        templateUrl: 'Content/partials/wish.html',
        controller: 'WishController'
      }).when('/list/:skip', {
        templateUrl: 'Content/partials/wish.html',
        controller: 'WishController'
      }).when('/hidden', {
        templateUrl: 'Content/partials/hidden.html',
        controller: 'HiddenController'
      }).when('/hidden/:skip', {
        templateUrl: 'Content/partials/hidden.html',
        controller: 'HiddenController'
      }).when('/about', {
        templateUrl: 'Content/partials/about.html',
        controller: 'AboutController'
      }).when('/privacy', {
        templateUrl: 'Content/partials/privacy.html',
        controller: 'AboutController'
      }).when('/support', {
        templateUrl: 'Content/partials/about.html',
        controller: 'AboutController'
      }).otherwise({
        redirectTo: '/'
      });
    }).run(function() {
      (function(d) {
        var id, js, ref;
        id = "facebook-jssdk";
        ref = d.getElementsByTagName("script")[0];
        if (d.getElementById(id)) {
          return;
        }
        js = d.createElement("script");
        js.id = id;
        js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=" + facebook_app_id;
        return ref.parentNode.insertBefore(js, ref);
      })(document);
      if (document.addEventListener) {
        return document.addEventListener('touchmove', function(e) {
          return e.preventDefault();
        });
      }
    });
  });

}).call(this);
