// Generated by CoffeeScript 1.7.1
(function() {
  define('./controllers/HiddenController', function(require, exports, module) {
    return module.exports = function($scope, logger) {
      return logger.info("Hidden items");
    };
  });

}).call(this);
