// Generated by CoffeeScript 1.7.1
(function() {
  define('./services/Logger', function(require, exports, module) {
    var Logger;
    Logger = (function() {
      toastr.options.timeOut = 2000;

      toastr.options.positionClass = 'toast-bottom-right';

      function Logger($log) {
        this.$log = $log;
      }

      Logger.prototype.error = function(message, title) {
        toastr.error(message, title);
        return this.$log.error("Error: " + message);
      };

      Logger.prototype.info = function(message, title) {
        toastr.info(message, title);
        return this.$log.info("Info: " + message);
      };

      Logger.prototype.log = function(message) {
        return this.$log.log(message);
      };

      Logger.prototype.success = function(message, title) {
        toastr.info(message, title);
        return this.$log.info("Success: " + message);
      };

      Logger.prototype.warning = function(message, title) {
        toastr.info(message, title);
        return this.$log.warn("Warning: " + message);
      };

      return Logger;

    })();
    return module.exports = Logger;
  });

}).call(this);
